server:
  port: 8090

spring:
  data:
    cassandra:
      keyspace-name: demo
      port: '9042'
      contact-points: 127.0.0.1
      schema-action: create_if_not_exists
      local-datacenter: datacenter1
  kafka:
    bootstrap-servers: 127.0.0.1:9092
